# Generated by Django 4.1.13 on 2025-04-25 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Paciente',
            },
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('registro_profissional', models.IntegerField()),
                ('especialidade', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Profissional',
            },
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sghss_app.paciente')),
            ],
            options={
                'db_table': 'Prontuario',
            },
        ),
        migrations.CreateModel(
            name='AgendamentoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sghss_app.paciente')),
                ('id_profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sghss_app.profissional')),
            ],
            options={
                'db_table': 'AgendamentoConsulta',
            },
        ),
    ]
